name: test_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # iOS style icons.
  cupertino_icons: ^1.0.8

  # Service locator
  get_it: ^9.2.0
  injectable: ^2.5.1

  # State manager
  flutter_bloc: ^9.1.1

  # HTTP networking
  dio: ^5.9.0
  retrofit: ^4.7.1
  logger: ^2.6.2

  # Streams
  rxdart: ^0.28.0

  # Comparing dart objects
  equatable: ^2.0.7

  # Code generator
  json_annotation: ^4.9.0

  # Routing
  go_router: ^17.0.1

  # UI

  # Utils
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Code generators
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.2

  #Lint rules
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

flutter_gen:
  l10n:
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    synthetic-package: false
    nullable-getter: false

dependency_overrides:
  analyzer: ">=8.4.0 <9.0.0"